"""2

Revision ID: 0260dba661c6
Revises: 1e8a1f337b30
Create Date: 2024-11-23 10:05:15.633241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0260dba661c6'
down_revision = '1e8a1f337b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('track_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('track_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
