"""3 commit

Revision ID: 1e8a1f337b30
Revises: 266c9ef195fc
Create Date: 2024-10-02 11:58:12.052958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8a1f337b30'
down_revision = '266c9ef195fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('meest_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meest_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
